Repository ember-bootstrap/ember-bootstrap-power-select, pull requests merged in 2022-04, with the labels that each got.

#300 drop support for node 10
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#303 upgrade ember-auto-import to v2
  package.json
  yarn.lock
Labels: breaking

#298 Address hasBlock deprecation: update to has-block
  addon/components/bs-form/element/control/power-select-multiple.hbs
  addon/components/bs-form/element/control/power-select.hbs
Labels: bug

#306 support Ember Bootstrap v5
  .github/workflows/ci.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: enhancement

#308 fix patterns not supported by Ember v4 in tests
  tests/integration/components/bs-form/element/control/power-select-multiple-test.js
  tests/integration/components/bs-form/element/control/power-select-test.js
Labels: internal
