Repository ember-bootstrap/ember-bootstrap-power-select, pull requests merged in 2023-02, with the labels that each got.

#350 drop support for Ember < 3.28
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#351 drop support for node 12
  .github/workflows/ci.yml
  package.json
Labels: breaking

#352 drop support for Ember Bootstrap v4
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#349 refactor to template-only components
  addon/components/bs-form/element/control/power-select-multiple.js
  addon/components/bs-form/element/control/power-select.js
Labels: internal

#353 drop support for ember-power-select v4 and v5
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#354 explicitly declare peer depencencies on ember-bootstrap, ember-power-select and ember-source
  package.json
Labels: breaking

#360 remove test scenario for Ember with jQuery
  .github/workflows/ci.yml
  config/ember-try.js
Labels: internal

#361 upgrade blueprint files to Ember CLI 4.10
  .ember-cli
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .prettierrc.js
  CONTRIBUTING.md
  README.md
  config/environment.js
  ember-cli-build.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  tests/integration/components/bs-form/element/control/power-select-multiple-test.js
  tests/integration/components/bs-form/element/control/power-select-test.js
  vendor/.gitkeep
  yarn.lock
Labels: internal

#346 Support Power Select's onKeydown argument
  addon/components/bs-form/element/control/power-select-multiple.hbs
  addon/components/bs-form/element/control/power-select.hbs
  tests/integration/components/bs-form/element/control/power-select-multiple-test.js
  tests/integration/components/bs-form/element/control/power-select-test.js
Labels: bug
