Repository ember-bootstrap/ember-bootstrap-power-select, pull requests merged in 2025-09, with the labels that each got.

#393 drop rsvp and fs-extra dependencies
  .npmignore
  blueprints/ember-bootstrap-power-select/index.js
  node-tests/blueprints/ember-bootstrap-power-select-test.js
  package.json
  yarn.lock
Labels: enhancement

#399 run blueprint tests in CI
  .github/workflows/ci.yml
Labels: internal

#396 ensure test coverage with ember-power-select v7 and v8
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  tests/dummy/app/app.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/config/ember-try.js
Labels: internal

#422 drop support for Ember classic (pre Octane)
  .github/workflows/ci.yml
  tests/dummy/config/ember-try.js
Labels: breaking

#424 upgrade from release-it-lerna-changelog to @release-it-plugins/lerna-changelog
  package.json
  pnpm-lock.yaml
Labels: dependencies

#425 upgrade with Ember CLI 4.12 blueprints
  .eslintrc.js
  .npmignore
  .stylelintignore
  .stylelintrc.js
  package.json
  pnpm-lock.yaml
  tests/dummy/app/styles/app.css
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
Labels: internal

#428 upgrade with Ember CLI 6.4 blueprints
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .prettierignore
  .prettierrc.js
  .stylelintignore
  .stylelintrc.js
  CHANGELOG.md
  README.md
  RELEASE.md
  addon/components/bs-form/element/control/power-select-multiple.hbs
  addon/components/bs-form/element/control/power-select.hbs
  blueprints/ember-bootstrap-power-select/index.js
  eslint.config.mjs
  node-tests/blueprints/ember-bootstrap-power-select-test.js
  package.json
  pnpm-lock.yaml
  renovate.json
  tests/dummy/app/app.js
  tests/dummy/app/deprecation-workflow.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
Labels: internal
